// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Product struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
